language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - sonar-scanner
install:
- ". travis-install.sh"
before_script:
- ". travis-before-script.sh"
script:
- ". travis.sh"
after_success:
- ". travis-after-success.sh"
notifications:
  webhooks:
    - http://travis.metatavu.io:7333/travisping