language: java

env:
  global:
    - secure: "GxyVYMqcxBzLbyvuPAubh9JnwFC3CTqgLhWFNQ4VkJ/b0Um1SXozkPfh/4jC\n1/QZtGr6VQrdgdb6ffPd0kA0zVV5HzspZMxSNuViO0V8E1ZkGwNmAi9U5Bv6\nLO5P68ba/xt2htSUt8RWP1xjp9UOn+JnD2JknAP9F7kmUcJhTDA="
    - secure: "H5/QkzkicdB5CiBjAt3HUA0iwrgL30y1Fg+w+wHqOijnBFy0GuP9FXSGw8UR\njfMLiel2pslzzBcCjYbfve99740A/UCPmqIJlBPXYH+8qqiK20/Q8LcjI6S2\nK1a+dNX+/NCZfmPxXLGW/C0sssPW3+kpRx/HNTirOLRRUGyFmbk="
    
after_success:
  - python travis/addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml